import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="next, next blog, my blog" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script src="/sc.js"></script> */}
      </Head>

      <Script src="/sc.js" strategy="lazyOnload"></Script>

      <nav className="main-nav">
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>Blog</li>
          <li>Contact</li>
        </ul>
      </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Blog!</a>
        </h1>

        <p className={styles.description}>
          Coding/Programming
          <code className={styles.code}>Blogs</code>
        </p>
      </main>

      <div className={styles.grid}>
        <div className={styles.card}>
          <h1>How to learn JavaScript</h1>
          <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti
            molestiae quod delectus, culpa in ad odit dignissimos voluptate,
            earum fugiat ipsum eaque alias animi. Illum illo commodi itaque
            dolor praesentium.
          </p>
        </div>
        <div className={styles.card}>
          <h1>How to learn JavaScript</h1>
          <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti
            molestiae quod delectus, culpa in ad odit dignissimos voluptate,
            earum fugiat ipsum eaque alias animi. Illum illo commodi itaque
            dolor praesentium.
          </p>
        </div>
        <div className={styles.card}>
          <h1>How to learn JavaScript</h1>
          <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti
            molestiae quod delectus, culpa in ad odit dignissimos voluptate,
            earum fugiat ipsum eaque alias animi. Illum illo commodi itaque
            dolor praesentium.
          </p>
        </div>
      </div>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
